FROM elasticsearch:7.8.1
# ADD https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.8.8/elasticsearch-analysis-ik-6.8.8.zip /tmp/
# RUN elasticsearch-plugin install -b file:///tmp/elasticsearch-analysis-ik-6.8.8.zip

RUN rm -rf /tmp/*

EXPOSE 9200 9300
